backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'rating'
    label: 'Takeaway Ratings'
    folder: 'content/rating'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{name}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Takeaway', name: 'takeaway', widget: 'string'}
      - { label: 'George's Rating', name: 'georgeRating', widget: 'string' }
      - { label: 'Josh's Rating', name: 'joshRating', widget: 'string' }
      - { label: 'Pete's Rating', name: 'peteRating', widget: 'string' }
      - { label: 'Overall Rating', name: 'overallRating', widget: 'string' }
      - { label: 'Notes', name: 'notes', widget: 'markdown' }